
// This file has been generated by the GUI designer. Do not modify.
namespace StrongMonkey.Client.GtkGui.Windows
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vboxBorderless;
		private global::Gtk.MenuBar menubar;
		private global::Gtk.Toolbar toolbar;
		private global::Gtk.VBox vbox;
		private global::Gtk.Notebook notebook;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Label label1;
		private global::Gtk.HBox hboxSessions;
		private global::Gtk.Button btnConnect;
		private global::Gtk.Button btnDisconnect;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget StrongMonkey.Client.GtkGui.Windows.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 266;
			this.Name = "StrongMonkey.Client.GtkGui.Windows.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("StrongMonkey");
			this.DefaultWidth = 266;
			this.DefaultHeight = 450;
			// Container child StrongMonkey.Client.GtkGui.Windows.MainWindow.Gtk.Container+ContainerChild
			this.vboxBorderless = new global::Gtk.VBox ();
			this.vboxBorderless.Name = "vboxBorderless";
			// Container child vboxBorderless.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar'/></ui>");
			this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar")));
			this.menubar.Name = "menubar";
			this.vboxBorderless.Add (this.menubar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxBorderless [this.menubar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxBorderless.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar'/></ui>");
			this.toolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar")));
			this.toolbar.Name = "toolbar";
			this.toolbar.ShowArrow = false;
			this.vboxBorderless.Add (this.toolbar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxBorderless [this.toolbar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vboxBorderless.Gtk.Box+BoxChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			// Container child vbox.Gtk.Box+BoxChild
			this.notebook = new global::Gtk.Notebook ();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 0;
			this.notebook.ShowBorder = false;
			this.notebook.ShowTabs = false;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.notebook.Add (this.vbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
			this.notebook.SetTabLabel (this.vbox1, this.label1);
			this.label1.ShowAll ();
			this.vbox.Add (this.notebook);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox [this.notebook]));
			w5.Position = 0;
			// Container child vbox.Gtk.Box+BoxChild
			this.hboxSessions = new global::Gtk.HBox ();
			this.hboxSessions.Name = "hboxSessions";
			this.hboxSessions.Spacing = 2;
			this.hboxSessions.BorderWidth = ((uint)(2));
			// Container child hboxSessions.Gtk.Box+BoxChild
			this.btnConnect = new global::Gtk.Button ();
			this.btnConnect.TooltipMarkup = "Start a new session.";
			this.btnConnect.CanFocus = true;
			this.btnConnect.Name = "btnConnect";
			this.btnConnect.UseUnderline = true;
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
			this.btnConnect.Image = w6;
			this.hboxSessions.Add (this.btnConnect);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxSessions [this.btnConnect]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hboxSessions.Gtk.Box+BoxChild
			this.btnDisconnect = new global::Gtk.Button ();
			this.btnDisconnect.TooltipMarkup = "Stop currently selected session.";
			this.btnDisconnect.CanFocus = true;
			this.btnDisconnect.Name = "btnDisconnect";
			this.btnDisconnect.UseUnderline = true;
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-disconnect", global::Gtk.IconSize.Menu);
			this.btnDisconnect.Image = w8;
			this.hboxSessions.Add (this.btnDisconnect);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxSessions [this.btnDisconnect]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox.Add (this.hboxSessions);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hboxSessions]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vboxBorderless.Add (this.vbox);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxBorderless [this.vbox]));
			w11.Position = 2;
			this.Add (this.vboxBorderless);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
